#!/bin/bash

cd /opt
wget https://archive.apache.org/dist/tomcat/tomcat-9/v9.0.65/bin/apache-tomcat-9.0.65.tar.gz
tar -xvf apache-tomcat-9.0.65.tar.gz
chmod 777 -R apache-tomcat-9.0.65
rm /opt/apache-tomcat-9.0.65/conf/tomcat-users.xml
cp /home/ubuntu/Tomcat-steup/tomcat-users.xml /opt/apache-tomcat-9.0.65/conf/
