#!/bin/bash

cd /opt
wget https://archive.apache.org/dist/tomcat/tomcat-9/v9.0.65/bin/apache-tomcat-9.0.65.tar.gz
tar -xvf apache-tomcat-9.0.65.tar.gz
chmod 777 apache-tomcat-9.0.65
cd apache-tomcat-9.0.65
cd conf
nano tomcat-users.xml
